/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as SingInIndexImport } from './routes/sing-in/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SingInIndexRoute = SingInIndexImport.update({
  path: '/sing-in/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/sing-in/': {
      id: '/sing-in/'
      path: '/sing-in'
      fullPath: '/sing-in'
      preLoaderRoute: typeof SingInIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sing-in': typeof SingInIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sing-in': typeof SingInIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/sing-in/': typeof SingInIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sing-in'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sing-in'
  id: '__root__' | '/' | '/sing-in/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SingInIndexRoute: typeof SingInIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SingInIndexRoute: SingInIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/sing-in/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/sing-in/": {
      "filePath": "sing-in/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
